#!/usr/bin/env bash
set -e

ENV_FILE="development.env"
COMPOSE_FILE="compose/development-compose.yml"

## Load .env only if it exists
#[ -f "$ENV_FILE" ] && export $(grep -v '^#' "$ENV_FILE" | xargs)

# Inject UID/GID for Unix-like systems
if [[ "$OSTYPE" != "msys" && "$OSTYPE" != "win32" ]]; then
	export HOST_UID=$(id -u)
	export HOST_GID=$(id -g)
fi

exec docker compose --env-file development.env -f development-compose.yml -f development-overrides.yml "$@"
