---
services:
  orinoco-db:
    environment:
    - POSTGRES_DB=${ORINOCO_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORINOCO_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORINOCO_DB_POSTGRES_USER}
    ports:
    - "${ORINOCO_DB_POSTGRES_PORT}:5432"
  orinoco:
    environment:
    - CABLE_DATABASE_URL=${ORINOCO_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${ORINOCO_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${ORINOCO_DB_DATABASE_URL}
    - QUEUE_DATABASE_URL=${ORINOCO_DB_QUEUE_DATABASE_URL}
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${ORINOCO_WEB_PORT}:3000"
    depends_on:
      orinoco-db:
        condition: service_healthy
        restart: true
      orinoco-db-cache:
        condition: service_healthy
        restart: true
      orinoco-db-cable:
        condition: service_healthy
        restart: true
      orinoco-db-queue:
        condition: service_healthy
        restart: true
  goaws:
    ports:
    - "${GOAWS_WEB_PORT}:4100"
  orinoco-db-cache:
    environment:
    - POSTGRES_DB=${ORINOCO_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORINOCO_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORINOCO_DB_CACHE_POSTGRES_USER}
    ports:
    - "${ORINOCO_DB_CACHE_POSTGRES_PORT}:5432"
  orinoco-db-cable:
    environment:
    - POSTGRES_DB=${ORINOCO_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORINOCO_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORINOCO_DB_CABLE_POSTGRES_USER}
    ports:
    - "${ORINOCO_DB_CABLE_POSTGRES_PORT}:5432"
  orinoco-db-queue:
    environment:
    - POSTGRES_DB=${ORINOCO_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORINOCO_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORINOCO_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${ORINOCO_DB_QUEUE_POSTGRES_PORT}:5432"
