services:
  railsapp:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: orinoco/railsapp
    ports:
      - "${ORINOCO_WEB_PORT}:3000"
    environment: &railsapp_environment
      - DATABASE_URL=${ORINOCO_DB_DATABASE_URL}
      - RAILS_ENV=test
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=5
      - SCOREBOARD_REDIS_URL=${SCOREBOARD_REDIS_URL}
      - EVENT_PIPELINE_GOAWS_URL=${EVENT_PIPELINE_GOAWS_URL}
      - OBS_HOST=${OBS_HOST}
    build:
      context: "./railsapp"
    depends_on: &railsapp_depends_on
      orinoco-db:
        condition: service_healthy
        restart: true
      scoreboard-redis:
        condition: service_healthy
        restart: true
  obs-bridge-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "ObsBridgeWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  twitch-bridge-worker:
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "TwitchBridgeWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  seven-tv-bridge-worker:
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "SevenTvBridgeWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  twitch-chat-projection-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "TwitchChatProjectionWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  clip-show-processor-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "ClipShowProcessorWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  tank-game-processor-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "TankGameProcessorWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  wos-brain-capture-worker:
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "WosBrainCaptureWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  wos-brain-processor-worker:
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "WosBrainProcessorWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
  wos-brain-projection-worker:
    image: orinoco/railsapp
    command: ["bundle", "exec", "rails", "runner", "WosBrainProjectionWorker.new.run"]
    environment: *railsapp_environment
    depends_on: *railsapp_depends_on
